version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: graph_postgres
    environment:
      POSTGRES_DB: graphdb
      POSTGRES_USER: graphuser
      POSTGRES_PASSWORD: graphpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U graphuser -d graphdb"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Ollama service
  ollama:
    image: ollama/ollama:latest
    container_name: graph_ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # Main application
  graph-gnn-app:
    build: .
    container_name: graph_gnn_app
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://graphuser:graphpass@postgres:5432/graphdb
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=mistral
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT:-us-west1-gcp}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME:-graph-embeddings}
      - MAX_BUDGET=${MAX_BUDGET:-500.0}
      - MAX_ITEMS=${MAX_ITEMS:-3}
      - MIN_CONFIDENCE=${MIN_CONFIDENCE:-0.6}
      - AUTO_ORDER=${AUTO_ORDER:-false}
      - ENABLE_MONITORING=${ENABLE_MONITORING:-true}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped

  # API Service
  graph-gnn-api:
    build: .
    container_name: graph_gnn_api
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://graphuser:graphpass@postgres:5432/graphdb
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=mistral
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT:-us-west1-gcp}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME:-graph-embeddings}
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "8000:8000"
    command: ["python", "api/fastapi_server.py"]
    restart: unless-stopped

  # Ollama model setup (runs once to pull Mistral)
  ollama-setup:
    image: ollama/ollama:latest
    container_name: ollama_setup
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=ollama:11434
    command: >
      sh -c "
        ollama pull mistral &&
        ollama pull nomic-embed-text &&
        echo 'Models pulled successfully'
      "
    restart: "no"

volumes:
  postgres_data:
  ollama_data: